ServerName localhost
Listen 8080

<VirtualHost *:8080>
    # El .py sigue funcionando
    WSGIScriptAlias /ATI/index.py /var/www/ATI/wsgi.py

    # Archivos estáticos (solo si NO son index.py)
    AliasMatch ^/ATI/(?!index\.py)(.*) /var/www/ATI/$1

    <Directory /var/www/ATI>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
